{
 "title": "mijnomgeving",
 "description": "Mijn Omgeving",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Sensor name",
    "query": "SHOW TAG VALUES WITH KEY = \"name\" WHERE \"name\" =~ /^EC/"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Water Temperature",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"waterTemperature\") AS \"metric\", \"Lat\" AS \"latitude\", \"Lon\" AS \"longitude\", \"name\"::tag AS \"name\" FROM /.*/ WHERE \"name\"::tag =~ /${name:regex}/ AND $timeFilter GROUP BY *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Water Electric Current",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "measurement": "/.*/",
     "query": "SELECT LAST(\"waterEC\") AS \"metric\", \"Lat\" AS \"latitude\", \"Lon\" AS \"longitude\", \"name\"::tag AS \"name\" FROM /.*/ WHERE \"name\"::tag =~ /${name:regex}/ AND $timeFilter GROUP BY *",
     "select": [
      [
       { "params": [ "Lat" ], "type": "field" },
       { "params": [ "latitude" ], "type": "alias" }
      ],
      [
       { "params": [ "Lon" ], "type": "field" },
       { "params": [ "longitude" ], "type": "alias" }
      ],
      [
       { "params": [ "waterTemperature" ], "type": "field" },
       { "params": [ "metric" ], "type": "alias" }
      ],
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/.*/",
     "query": "SELECT waterTemperature FROM /.*/ WHERE \"name\"::tag =~ /${name:regex}/ AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Electric Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/.*/",
     "query": "SELECT waterEC FROM /.*/ WHERE \"name\"::tag =~ /${name:regex}/ AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/.*/",
     "query": "SELECT batteryVoltage FROM /.*/ WHERE \"name\"::tag =~ /${name:regex}/ AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}